import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "BioCure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              fontWeight: "bold",
            },
            success: {
              style: {
                color: "green",
              },
            },
            error: {
              style: {
                color: "red",
              },
            }
          }}
        />
      </body>
    </html>
  );
}
